src/Entity/Dinosaur.php
<?php
namespace App\Entity;

use App\Enum\HealthStatus;

class Dinosaur
{
    private string $name;
    private string $genus;
    private int $length;
    private string $enclosure;
    private HealthStatus $health = HealthStatus::HEALTHY;
    public function __construct(string $name, string $genus = 'Unknown', int $length = 0, string $enclosure = 'Unknown')
    {
        $this->name = $name;
        $this->genus = $genus;
        $this->length = $length;
        $this->enclosure = $enclosure;
    }
    public function getName(): string
    {
        return $this->name;
    }
    public function getGenus(): string
    {
        return $this->genus;
    }
    public function getLength(): int
    {
        return $this->length;
    }
    public function getEnclosure(): string
    {
        return $this->enclosure;
    }

    public function getHealth(): HealthStatus
    {
        return $this->health;
    }

    public function getSizeDescription(): string
    {
        if ($this->length >= 10) {
            return 'Large';
        }

        if($this->length >= 5) {
            return 'Medium';
        }

        
        return 'Small'; 
    }

    public function setHealth ( HealthStatus $health): void
    {
        $this->health = $health;
    }

   
    public function isAcceptingVisitors(): bool
    {
        return $this->health !== HealthStatus::SICK;
    }
    
}

src/Controller/DinoController.php
<?php
namespace App\Controller;

use App\Entity\Dinosaur;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\GithubService;

class DinoController extends AbstractController
{
    #[Route(path: '/', name: 'app_dino', methods: ['GET'])]
    public function index(GithubService $githubService): Response
    {
        $dinos = [
            new Dinosaur('Daisy', 'Velociraptor', 2, 'Paddock A'),
            new Dinosaur('Maverick','Pterodactyl', 7, 'Aviary 1'),
            new Dinosaur('Big Eaty', 'Tyrannosaurus', 15, 'Paddock C'),
            new Dinosaur('Dennis', 'Dilophosaurus', 6, 'Paddock B'),
            new Dinosaur('Bumpy', 'Triceratops', 10, 'Paddock B'),
        ];
        foreach ($dinos as $dino) {
            $dino->setHealth($githubService->getHealthReport($dino->getName()));
        }
        return $this->render('dino/index.html.twig', [
            'dinos' => $dinos,
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        {% block stylesheets %}
        {% endblock %}

        {% block javascripts %}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/dino/index.html.twig
 {% extends 'base.html.twig' %} 

 {% block body %}
 <div class="jumbotron jumbotron-fluid rounded bg-info text-white my-2 my-lg-5 py-2 py-lg-4">
     <div class="container text-center ">
        <h1 class="display-4">Welcome to the Dinoland</h1>
        <p class="lead">This page shows schedule of dinosaurs at their habitat...</p>
     </div>
</div>
 <header></header>
     <div class="table-responsive-md">
        <table class="table table-hover">
            <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Genus</th>
                <th scope="col">Length</th>
                <th scope="col">Size</th>
                <th scope="col">Enclosure</th>
                <th scope="col">Accepting Visitors</th>
                </tr>
            </thead>
            <tbody>
                
                {% for dino in dinos %}
                <tr>
                    <th scope="row"></th>
                    <td>{{ dino.name }}</td>
                    <td>{{ dino.genus }}</td>
                    <td>{{ dino.length }}</td>
                    <td>{{ dino.sizeDescription }}</td>
                    <td>{{ dino.enclosure }}</td>
                    <td>{{ dino.acceptingVisitors ? 'Yes' : 'No'}}</td>
                </tr>
                {% endfor %}
               
            </tbody>
            </table>
     </div>

     <div class="jumbotron jumbotron-fluid rounded bg-info text-white my-2 my-lg-5 py-2 py-lg-4">
     <div class="container text-center ">
        <h1 class="display-4">Goodbye from the Dinoland</h1>
        <p class="lead">I hope we will see You soon ...</p>
     </div>
</div>
 {% endblock %}